### ISSUE TITLE
Retags does not work

### ISSUE THREAD

**Issue by laurajax** [new-xkit/XKit#105]
Retags has not displayed the tags on reblogs for me ever since some time ago on old xkit; it was one of the first extensions to stop working. When it didn't work on New Xkit I assumed that was to be expected, until I saw you guys answering asks as if it was working. 

I disabled all other chrome and xkit extensions except for Retags, and it still does not work. I have Retags 0.6.6

**Comment by Schmaiffe** [comment]
Heya, I'm not a programmer or anything, but I had problems with retags on the old xkit and found out it was a third party extension, which can be found here: https://github.com/alexhong/tumblr-retags

In my case, even the new version didn't work because of a problem with the cache, so the dev very kindly made a no-cache version, here: https://github.com/alexhong/tumblr-retags/blob/master/tumblr-retags-nocache.user.js#_=_ which is what I use now and it still works for me. I hope this is helpful to you! If you install that, it's best to uninstall any other versions of retags including the xkit extension.

**Comment by laurajax** [comment]
Thank you! Both versions work for me on normal notifications and the activity page, but for whatever reason the notifications that come up from the xkit extension "classic notifications" only show the tags for a split-second before they disappear. This happens with both the cache and non-cache versions of the extension. I wonder what's causing that?

**Comment by nightpool** [comment]
@laurajax Just to be clear—do you or do you not have a problem with the retags from the XKit extension gallery?

**Comment by laurajax** [comment]
Xkit retags has not worked for me ever since old xkit. I stopped using it 5 days ago when schmaiffe linked me to the non-xkit version, but if you've made changes to it I can check the xkit version again.

**Comment by laurajax** [comment]
Xkit retags has not worked for me since old Xkit. I stopped using it and used the version that Schmaiffe linked me to, but just now I disabled it and re-installed the Xkit version, and it seems to work fine now! Did you guys update it in the last few days? Or did installing the standalone version of it somehow fix my Xkit version?

**Comment by laurajax** [comment]
However, the tags still don't show up in the "classic notifications" notifications. They seem to load correctly upon installing the extension, but once I load or reload a new page they stop appearing. But it works fine in the activity page and in the pop-up from clicking on a post's notes,.

**Comment by nightpool** [comment]
@laurajax seems like a different bug! can you file a new ticket? Thanks!

glad to know things started working again for you
