### ISSUE TITLE
Can't uninstall or disable Old Sidebar

### ISSUE THREAD

**Issue by ShotgunsAndSass** [new-xkit/XKit#1050]
I've tried re-installing multiple times. It doesn't work unless I do that any more and it suddenly stopped letting me today. it works on my other chrome user, but not this specific one. I've removed cookies, tried everything but it won't work. I'm about to try manually re-installing everything without using te import, but there's no reason why it should be that and I can't work out why my user would specifically have this issue. Does anyone have any ideas?

**Update:** It didn't work, this happens whether the settings are imported or not.

**Update 2:** It won't let me reset or delete it either, it's like the specific extension has frozen and reinstalling everything does nothing.

**Comment by ShotgunsAndSass** [comment]
It didn't work, this happens whether the settings are imported or not.

**Comment by nightpool** [comment]
Seems to be only on Firefox. P-High because it causes major issues (entire pages rendered unclickable, "frozen" account menu, and more have been reported) and prevents users from fixing those issues, making a reset or manually deleting the extension in xkit_editor (something users won't know how to do) the only option.

**Comment by nightpool** [comment]
Seems to only be on Firefox

P-High because it causes major issues on the page (not being able to click on any links, "frozen" account menus, and more have been reported), and prevents users from being able to fix those issues (making resetting xkit or manually deleting the extension through xkit_editor, something users won't know how to do, the only option).

@estufar can you take a look at this?

**Comment by nightpool** [comment]
#1034 seems to be related (and has more discussion)

**Comment by Dhwty** [comment]
Manually applying #1077 via xkit_editor solves this problem (but the sidebar is not the right width for the _new_ tumblr layout, so it squishes native sidebar content a bit). I've been using it since Estufar posted it last year, and it hasn't given me any problems, yet.

**Comment by nightpool** [comment]
It solves the problem of uninstalling it, or just the problem of it being unresponsive?

**Comment by Dhwty** [comment]
You can definitely uninstall the fix version. The uninstall problems are directly related to the unresponsiveness. 

I actually mangled together a walkthrough to uninstall the broken version, in #1034 , last April. Basically, you have to click to disable it *three times* and then everything else proceeds as normal. 

> Three clicks on the tickbox to disable. One click does nothing (which makes me think it's deselecting something somewhere else on the page). Two clicks successfully spawns the sidebar. A third click disables the extension and removes the sidebar. A fourth click re-enables the extension and re-spawns the sidebar.

**Comment by nightpool** [comment]
okay, I'll fast track getting #1077 merged then, thanks.

**Comment by nightpool** [comment]
Should be fixed by #1302. Let us know if you're still seeing this after updating to old sidebar 1.2.0!
