### ISSUE TITLE
known issue from original xkit - multifox and one-click postage won't work together

### ISSUE THREAD

**Issue by hanharr** [new-xkit/XKit#108]
first of all thanks for working on xkit! is there any chance that the issue where multifox and xkit's one-click postage extension don't get along is something you guys can fix? for reference, my default profile on firefox uses the extension just fine but when i switch to another profile in multifox, xkit responds with the "i could not draft/queue/reblog your post" error. if you guys can figure out what's preventing one-click postage working with multiple firefox profiles that would be a lifesaver, as multifox is a huge priority for me with tumblr blogging but i've been using one-click postage for so long that regular tumblr reblogging feels super tedious.

**Comment by hobinjk** [comment]
I believe that the way Multifox works makes it so that XKit mistakenly identifies itself as the first blog you were logged into. This probably should be reported as a bug in Multifox because they should be properly creating different cookie jars for different profiles and this suggests that they aren't.

**Comment by hanharr** [comment]
got it! i'll submit a bug report with multifox to see if i can get them to take a look at it :)

**Comment by nightpool** [comment]
closing until we hear back from multifox
