### ISSUE TITLE
Unable to click anything from time to time. 

### ISSUE THREAD

**Issue by ribos9178** [new-xkit/XKit#1202]
Every once in a while, nothing works when I click on it, whether it's the like button, reblog, or going into my blog page. I'm pretty sure it's an XKit problem since disabling it temporarily seems to resolve the issue.

**Comment by DarkPuck** [comment]
I've been having this issue for several weeks. On my personal blog, it's bad enough that I have to refresh the page several times before I can click again. I have discovered that right-clicking works, so I could reblog something if I opened the link in a new tab/window.

I've been playing around with the extensions I run in XKit, and I _think_ it's a conflict between Old Sidebar and Tag Tracking+

I'm using Chrome and Windows 7.

**Comment by MyshkaMoya** [comment]
I'm not using Old Sidebar, and Tag Tracking+ is deactivated. So - no, I dont think that's the reason.

**Comment by MyshkaMoya** [comment]
Also, yes, right-clicking works. It's just the regular click on links/buttons. I tried deactivating anti-capitalism and for a while it seemed to work. but not anymore. 

Update: I threw out a couple things I dont need anymore, and for the moment it seems to work. 
Here a summary of my currently installed extensions:
https://gist.github.com/1e6ece9d9a082b49ad01a9046c00152e

**Comment by particledamage** [comment]
I am also having this issue. I got rid of anti-capitalism but it's still happening. I'll mess around w/ non-essentials to see if I can get it to last without having to constantly refresh just to like one post.

**Comment by particledamage** [comment]
I got rid of "Old Stats" and it's been working fine.

**Comment by Wolvan** [comment]
Possibly a problem with Old Stats, yeah. @nightpool I'd say it's time to get rid of the broken as hell extension anways, what do you say?

**Comment by nightpool** [comment]
I *think* https://github.com/new-xkit/XKit/pull/956 should be good to go?
we didn't decide if we needed to message it or how

**Comment by TrixieBastard** [comment]
This is not an "every now and then" problem for me -- this is an "every day, multiple times a day" problem. I'll have to refresh my dash six or seven times in a row sometimes before buttons/links work correctly again.  also, getting my account menu to work is generally out of the question even if other buttons are working as they should be, but I feel like it's related to this problem bc it didn't exist prior to the whole "no click" thing. 

anyway, I'll check out the config mentioned above to see if it helps (because lbr, tumblr is AWFUL without xkits New or Old. I disabled New because I could no longer deal with not being able to click on anything and was swiftly reminded of how much i super hate the vanilla tumblr experience. ugh)

**Comment by citizencold** [comment]
I've been having this issue every day for over a month, I thought I was the only one experiencing this.

**Comment by nightpool** [comment]
Should be fixed by #1302. Let us know if you're still seeing this!
