### ISSUE TITLE
Editing posts with ER is broken

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#1205]
very recent regression

1. reblog a post to your drafts, trim some content
2. go to your drafts
3. click "edit"
4. click "save".
5. notice that the saved version doesn't have the `<xkit>` tags, and thus is broken.

not sure how much of this is required, but its definitely a problem with not handling edits correctly

**Comment by blackjackkent** [comment]
@nightpool I'm poking a little at a good way to fix this but if this makes anything clearer on your end (since you wrote the latest workflow) -- this seems to have something to do with the fact that a) `reblog_tree_exists()` returns false when editing a post that has already been ER-ed and b) `edit_the_reblogs()` only fires when clicking the edit icon, which there's no need to do when editing a post where you've already clicked it and trimmed things, so those `<xkit>` tags never get added.

**Comment by nightpool** [comment]
Yeah, for sure. it's just a hard problem.

**Comment by nightpool** [comment]
We need to split the "publish the post with ER" part of things from the "actually transform this post into a blockquote-ready equivalent", possibly based on a heuristic.

**Comment by nightpool** [comment]
(although maybe if you have ER installed we should always publish the post with ER, just in case?)

**Comment by nightpool** [comment]
I guess another option is, instead of `<xkit>`, we use something that persists across editing. That might be a little simpler. (And then we could probably just rip out the "send to server with ER" code)

**Comment by blackjackkent** [comment]
That might be an easier approach tbh (and more nearly mimics what people were doing to get around this problem before the latest fix, also.) Something like bolding the colon is enough to flip things to block quotes without changing the user display particularly noticeably, I think. 

> a tag around the url, inside of the a tag

Not sure what you mean by this; can you clarify?

**Comment by nightpool** [comment]
@blackjackkent if my memory serves me (might be worth going back and double
checking—I think I sent the post to you on gitter a while back?) the
structure was <a href="whatever"><g>nightpool</g></a>

**Comment by blackjackkent** [comment]
@nightpool Wouldn't that have the same problem as the <xkit> tag, since you're still adding a custom HTML element to the post structure?

> I guess another option is, instead of <xkit>, we use something that persists across editing.

I'm inclined to say this is the best bet. Something like `<a href="whatever">nightpool<b>:</b></a>` when we're populating the blockquotes and then it can just go on its merry way and we don't have to worry about further manipulating it.

**Comment by nightpool** [comment]
@blackjackkent <g> isn't technically a custom element, its part of the SVG
standard. it seemed to slip through for some reason.

I'd have to do most research to confirm this.
