### ISSUE TITLE
xkit can't update :( 

### ISSUE THREAD

**Issue by westminsterabi** [new-xkit/XKit#1238]
i keep getting the "can't update" error message, it's been going on for several days

**Comment by nightpool** [comment]
Hello. Unfortunately, we don't currently provide support for New XKit on Github. Instead, we use it to track bugs and defects in New XKit. We can provide support for you in our Gitter chat: https://gitter.im/new-xkit/support.

With that in mind, here are some common causes for seeing this issue:

 - You're using old XKit, a piece of software that hasn't been maintained by it's author in over 2 years. We run and maintain New XKit, which is a fork, or copy, of XKit, but is a distinct piece of software that you need to install **instead** of XKit.

   If your version of XKit is blue, or older then 7.7.X, you won't be able to receive updates from the New XKit team.

 - You have a piece of software installed that's prevent New XKit from checking for updates. Privacy Badger is an example of software that has been known to have this conflict, but their may be others, such as over-zealous ad blockers.

 - You're using Safari, and your Safari or Mac OS version is out of date. We currently only support Safari 10, and we're looking into known problems with El Capitan and haven't been able to diagnose them yet due to a lack of development hardware to do so with.

As I mentioned initially, please stop by Gitter for further support.
