### ISSUE TITLE
[Code: 101] Can't Reach XKit Servers

### ISSUE THREAD

**Issue by shizlist** [new-xkit/XKit#1268]
Hello,

  I am getting this error popup consistently--> [Code: 101] Can't Reach XKit Servers

  And xkit is currently not functioning. The icon is in my browser menu, but does not appear on my tumblr page.

  I have the latest version of both xkit and Chrome. I've followed all of the steps in the troubleshooting guide (though I can't access xkit settings because 'options' is greyed out in the xkit menu). I've disabled firewalls, I've re-downloaded and re-installed xkit. I've created a new user in Chrome, but the error persists.

   Little help?

Thanks!

**Comment by blackjackkent** [comment]
Hello! Generally we prefer to accept support questions like this in our [live chat](https://new-xkit-support.tumblr.com/support). Off the top of my head, though, this usually means you have downloaded Old XKit rather than New XKit. If you navigate to [chrome://extensions](chrome://extensions), you can see the version of XKit you have installed. If it is 7.5.x, you have downloaded Old XKit.

We are a separate project which branched off from old XKit when the previous maintainer stopped working on it; we don't have access to the old XKit code. New XKit is version 7.7.x and can be downloaded from [here](https://chrome.google.com/webstore/detail/new-xkit/inobiceghmpkaklcknpniboilbjmlald#_=_). Make sure to uninstall the old version before installing the new one.

If this doesn't solve your issue, feel free to swing by the support chat. :)

**Comment by shizlist** [comment]
Holy crap, you are a LIFE SAVER. I didn't even know that the old xkit was out of commissions. I just downloaded the new xkit, and it is working perfectly. Thank you!!
