### ISSUE TITLE
Links don't work, presumably because of an interaction between Old Sidebar and something else

### ISSUE THREAD

**Issue by citrusella** [new-xkit/XKit#1306]
When I have Old Sidebar enabled, all links on my dash (and on other pages, often) stop working. That includes links/linked images (i.e. bringing up photos or clicking the url on a post or clicking the corner of a post to go to the blog) as well as things that bring up windows, like the activity button or the notes link or the XKit button. I was asked in #1303 to bring this issue here.

[Here's a link to my list of installed extensions.](https://gist.github.com/97ac05873bc6d5f6da3acf7207aa8aae) (Old Sidebar is disabled in the list because it was the only way to get the menu open to export it, but it's been enabled during the extent of the problems since last night.)

I'd been having intermittent (maybe 1-5% of the time) link issues before the update to Old Sidebar, but I thought it was something on Tumblr's end back then and a refresh always fixed it.

EDIT: 1304 (which fixes 1303) did not fix this as far as I can tell, if that info helps at all.

**Comment by nightpool** [comment]
thanks for writing up this issue! can you jump into chat sometime so we can try and diagnose it?

Otherwise, it would be really helpful to have a full config export, and a screenshot of about:addons

you'd probably want to send the full config export privately over chat, since it includes all of your XKit information, including outbox, archived posts, etc.

**Comment by nightpool** [comment]
I've confirmed this on Firefox 53 and Old Sidebar version 1.2.1.
