### ISSUE TITLE
Old Sidebar not working on Firefox

### ISSUE THREAD

**Issue by notapaladin** [new-xkit/XKit#1311]
I have the latest version of Firefox and the latest version of Old Sidebar and it's not working. Is this a known bug? If yes, does anyone have any tips for fixing it?

**Comment by nightpool** [comment]
Old Sidebar is currently disabled on Firefox due to severe bugs. I meant to post an announcement about this and forgot.

**Comment by Ithilwen** [comment]
Thanks for letting us know, but is anyone working on a fix? I don't know about others but it's been broken for several months on my end.

**Comment by nightpool** [comment]
P-High because it's a reasonably popular extension being completely disabled.

**Comment by m2pt5** [comment]
Possibly related, I cannot seem to uninstall Old Sidebar. When I click the "Yes, uninstall", it just hangs there.

**Comment by Dhwty** [comment]
@m2pt5 Assuming this is the same 'can't uninstall' that Old Sidebar used to have, I actually mangled together a walkthrough to uninstall the broken version, in #1034 , last April. Basically, you have to click to disable it *three times* and then everything else proceeds as normal. 

> Three clicks on the tickbox to disable. One click does nothing (which makes me think it's deselecting something somewhere else on the page). Two clicks successfully spawns the sidebar. A third click disables the extension and removes the sidebar. A fourth click re-enables the extension and re-spawns the sidebar.

**Comment by m2pt5** [comment]
@Dhwty I don't think it's the same 'can't uninstall'. I can get the appearance of the "Enable Old Sidebar" button to change by clicking it then the Old Sidebar icon on the left again, with no change on the page in the background, but regardless of which state it's in, the uninstall just sits there.

**Comment by TheJRC** [comment]
Not sure if it would be prudent to open a new issue for this, but this one is still Open, so I suppose I could post it here? Although the last post here was in August.

I tried testing out Old Sidebar because I was just fiddling with a bunch of extensions to see how they looked and what they did, uninstalling the ones I decided I didn't need. Old Sidebar seemed to be completely busted, nothing popped up at all. I wasn't sure if it's just broken or if there's something else on my browser that's messing with it. Regardless, now I can't uninstall it. I've tried several things, including @Dhwty 's method, which apparently no longer works in Firefox Quantum (I have the latest version, 58.0.2 64-bit). Clicking to disable the extension does not un-bubble the tickbox no matter how many times I click, though I have gotten it to disable after clicking the tickbox once and refreshing the page. It still will not uninstall, though. I tried disabling all my other extensions (part of another solution I found by browsing this Github), and it still won't uninstall.

I have no idea if this extension is still disabled for bugs (as @nightpool said above, but that post was almost a year ago), but considering it's sitting there in the XKit Extensions list, I expected it to work. It doesn't, and now I can't rid of it. Any suggestions?

**Comment by Dhwty** [comment]
I'm going to assume you can get to the Xkit control panel, since you're actually trying to do the unticking thing. So, from there, go to the 'Other' tab.

- Scroll down on the left and select 'Xkit Editor'
- Right-click the 'Open Xkit Editor' button and open in new tab
- Go to that tab
- Click 'Open' on the left side of the editor
- Select 'estufars_sidebar_fix' from the list
- When it opens up, click 'Delete' on the left
- Tell the confirmation you really do mean it
- Switch back to the other tab and reload your dash

It *should* uninstalled.

**Comment by TheJRC** [comment]
@Dhwty  Yep, that did it. I was unaware of that raw editor over there in "Other." I'll remember it next time something breaks. Thanks for your help.
