### ISSUE TITLE
Activity+ does not filter activities by type

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#1314]
The filter thing appears, but selecting a filter does nothing.

(split from #1312)

**Comment by Quillot** [comment]
Tried tinkering with the code. I just started with XKit this morning, and I haven't been learning Javascript that long so forgive me for any bad coding.

I'm not sure about the minute features of Activity+ since i've never used it, but I tried to restore some of the functionality.

	if (m_type === "from_mutual") {
		// originally ui_note
            // used activity notification:not to select all divs that arent class is_friend
		XKit.tools.add_css(".ui_notes { display: block; } .ui_notes .activity-notification:not(.is_friend) { display: none; }", "activity_plus_note_filter_mutual");
		return;
	}

	......

	var m_filter_css = ".ui_notes { display: block; } .ui_notes .activity-notification:not(." + m_type + ") { display: none; }";

With these changes, filters are implemented on the ui_notes. Haven't tested it for mentions, and it doesn't work for replies. It's maybe just a possible step towards restoring Activity+.

date_header divs also aren't dealt with yet, still trying to figure that out as well. I've only gone through half of the original code, so maybe I missed something. I'm also not sure if its possible to use a window listener except for dashboard (can't find if there is in the docs).

Thanks for reading :) I'll try to continue working on it just to contribute as much as I can.

**Comment by Kvothe1970** [comment]
Just a heads up, this still seems to be broken. Now the filter groups the same day multiple times: 

![1](https://cloud.githubusercontent.com/assets/24984994/26537135/1d4de702-443d-11e7-92b7-912dc2973886.png)

**Comment by nightpool** [comment]
@Kvothe1970 that's how it always has worked—if there aren't a lot of the type of activity you're looking for, it has to "scroll through" a bunch of pages to get to them. So if you have multiple pages of notes from the same day, it'll show "TODAY" multiple times.

If you scroll all the way to the bottom, it will load things for as long as it can.

**Comment by Kvothe1970** [comment]
Ah cheers, that must have been the effect of getting a lot more notes than usual. Thank you, for clearing this up!
