### ISSUE TITLE
Classic Notifications broken by the new Activities update

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#1318]
Scope of brokenness is unknown, but we've had two people in chat asking about it.

tagging #1312 for metabug purposes

**Comment by ElliSpeaks** [comment]
Mine is broken as well. Please let me know if there's anything I can send to help with troubleshooting!

**Comment by improbablelogic** [comment]
Mine's been broken since the update, on all my blogs. Let me know if I can be off help!

**Comment by katyggls** [comment]
Will this extension be getting a fix soon or is it one of the things that is not fixable? It's just really hard to use the activity page for anything useful, especially since you can't use notification block or one click replies from the activity page. For me at least, that's a lot of the main functionality of xkit.

**Comment by ElliSpeaks** [comment]
Any updates? My activity page doesn't always work so I depend on Classic Notifications to tell me what's going on.
