### ISSUE TITLE
"No recommended 2.2.1" still shows reccomended posts

### ISSUE THREAD

**Issue by andrewmyles** [new-xkit/XKit#1419]
Today I saw once again posts on my dash from blogs I don't follow. Until now, I've been using both tumblr saviour and the No Recommended addon to hide those, but sadly, they came back, and it is frustrating. I've tested it on the newest Xkit, both under Chrome and Firefox, on Windows 7.

**Comment by AshEaria** [comment]
I believe this might be because Tumblr has just rolled out a new way to show recommended posts, shoving what would usually be on Tumblr radar at the very top of the dash. These posts contain an element with class .recommendation-reason-footer that shows the "staff pick" message at the bottom of the post in red. This comment is purely informational for the developers to have more information on this issue.

**Comment by ThePsionic** [comment]
Should be fixed by #1420 - feel free to re-open if the issue hasn't been fixed.
