### ISSUE TITLE
extension gallery

### ISSUE THREAD

**Issue by abookie** [new-xkit/XKit#151]
just installed the new xkit, appears perfect and i love it. but there are some extensions that i want to add and every time i click on the extension gallery it's just continuously loading and never brings up the extensions. i've tried uninstalling and updating chrome even and it hasn't seemed to fix it. i installed xkit for the use of the extensions but haven't even been able to see them yet. anyone else have this problem or know of a fix?! would greatly appreciate it!! (:

**Comment by nightpool** [comment]
Can you make sure you're on the most up to date version? We recently moved the extension library and its possible you might not bee reaching the correct one. 

the newest version of xkit is 7.7.0. You can see your xkit version in the "About + Support" section of the menu.

**Comment by abookie** [comment]
yes i just checked it and i do have the current version.

**Comment by nightpool** [comment]
Can you access http://new-xkit.github.io/XKit/Extensions/dist/page/gallery.json from your web browser?

**Comment by abookie** [comment]
just looks like a page full of letters and code?
<img width="1251" alt="screen shot 2015-08-06 at 12 56 56 pm" src="https://cloud.githubusercontent.com/assets/13683981/9121964/c8015b46-3c3a-11e5-87bf-d00174e9c87b.png">

**Comment by nightpool** [comment]
@abookie that's how its supposed to look. Just making sure something wasn't blocking you from seeing it.

**Comment by WyohKnott** [comment]
Do you have an ad-blocker or something like that, with a "tight" configuration (like Default Deny 3rd party ressources)?

**Comment by hobinjk** [comment]
An ask has this problem with https://gist.github.com/anonymous/5c6e8d0c98cec2e93098 on chrome and windows 8.1. I'm going to ask them about ad-blocking and Chrome's CSP.

**Comment by comealongraggedypond** [comment]
Hi, I just uninstalled the old xkit, installed the new one through Chrome, and I'm having this same problem. I can also access the link that was provided earlier and pausing my Chrome AdBlocker has not solved the problem.

**Comment by Wolvan** [comment]
@comealongraggedypond @abookie can you guys open the chrome javascript console and gives us the log from there?

**Comment by turiel** [comment]
I was having this issue as well (with Google Chrome on Windows 8.1). In own trouble shooting and testing to see if any other extensions on Chrome were interfering with xKit, I noticed that my Chrome was way out of date and for some reason had stopped auto-updating itself. I wound up reinstalling the latest version of Chrome and it started working again. 

So, perhaps the issue has something to do with an out of date browser?

**Comment by comealongraggedypond** [comment]
@turiel I'll try reinstalling Chrome and see if that's interfering - thank you!

@Wolvan here's the log when I try to open the extensions gallery:

7
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.3), not all, only screen and (-webkit-min-device-pixel-ratio: 1.3020833333333333), only screen and (min-resolution: 125dpi), only screen and (min-resolution: 1.3dppx) dashboard:1
20
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 2), not all, not all, only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) dashboard:1
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.5), not all, only screen and (min-resolution: 144dpi), only screen and (min-resolution: 1.5dppx) dashboard:1
2
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.3), not all, only screen and (-webkit-min-device-pixel-ratio: 1.3020833333333333), only screen and (min-resolution: 125dpi), only screen and (min-resolution: 1.3dppx) dashboard:1
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 2), not all, not all, only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) dashboard:1
3
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.3), not all, only screen and (-webkit-min-device-pixel-ratio: 1.3020833333333333), only screen and (min-resolution: 125dpi), only screen and (min-resolution: 1.3dppx) dashboard:1
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.5), not all, only screen and (min-resolution: 144dpi), only screen and (min-resolution: 1.5dppx) dashboard:1
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.3), not all, only screen and (-webkit-min-device-pixel-ratio: 1.3020833333333333), only screen and (min-resolution: 125dpi), only screen and (min-resolution: 1.3dppx) dashboard:1
[XKit Bridge] Hello from Bridge 2.1 bridge.js:60
[XKit Bridge] Retrieving storage.. bridge.js:61
[XKit Bridge] Storage loaded, calling XKit.. bye! bridge.js:88
[XKit Bridge] Hello from Bridge 2.1 bridge.js:60
[XKit Bridge] Retrieving storage.. bridge.js:61
init_extension: {"standard":true,"ask_frame":false,"blog_frame":false,"peepr":false,"xkit":false} xkit.js:656
Trying to run xkit_main. xkit.js:656
Welcome from XKit Main 1.3 REV B xkit.js:656
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 2), not all, not all, not all, only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) dashboard:1
XKit Pack Launcher working. xkit.js:656
Running xkit_patches (version 3.1.11) xkit.js:656
XKit Main: Fast-boot mode xkit.js:656
[XKit Bridge] Storage loaded, calling XKit.. bye! bridge.js:88
1794 VM324:83
Object
 VM324:436
Checking for XKit News xkit.js:656
Trying to fetch: https://www.xkitcs.com/seven/paperboy/index.php?ftch_id=Z1O13kmWDW5cLw5fpVReezdd0Cm8fj xkit.js:656
Trying to fetch: https://www.xkitcs.com/seven/framework_version.php?ftch_id=eeqz6bK4bKhC9ixLtlC374TWhvXl3S xkit.js:656
Updates: difference = 49429767 xkit.js:656
Starting update checking.. xkit.js:656
No packs found to update. VM325:101
The page at 'https://www.tumblr.com/dashboard' was loaded over HTTPS, but displayed insecure content from 'http://31.media.tumblr.com/avatar_b5acef4abf8c_64.png': this content should also be loaded over HTTPS.
 dashboard:1
Enabled extensions: xkit_patches, xkit_preferences, xkit_updates, xinbox, one_click_postage, one_click_reply, tweaks xkit.js:656
Disabled extensions: go_to_dash(not in frame) xkit.js:656
init_extension: {"standard":false,"ask_frame":false,"blog_frame":false,"peepr":false,"xkit":false} xkit.js:656
Booted XKit up in 543 milliseconds. xkit.js:656
download.extension of 'one_click_postage' was successful. Calling callback. xkit.js:656
Updated one_click_postage xkit.js:656
2
Fetch successful, calling callback. xkit.js:656
Uncaught TypeError: Cannot read property 'version' of undefined dashboard:392
download.extension of 'tweaks' was successful. Calling callback. xkit.js:656
Updated tweaks xkit.js:656
Uncaught TypeError: Object accesskit has no method 'startsWith' dashboard:1080
Resource interpreted as Image but transferred with MIME type text/plain: "https://ums.adtechus.com/mapuser?providerid=1004;getuser=https://ads.yahoo.…/user-match?nid=606282&eid=$UID&y=l_8fsYY_Gn0MYCcnTzNQTf23mNfQ7zKpwoAGcg--". r-sf.html:1
event.returnValue is deprecated. Please use the standard event.preventDefault() instead. g-r-min.js:2

**Comment by comealongraggedypond** [comment]
@turiel Updating Chrome worked! Thank you!

**Comment by 0xazure** [comment]
Closing as per #472 and #617 this is a problem with older versions of Chrome.
