### ISSUE TITLE
Blog Tracker not working since Yesterday

### ISSUE THREAD

**Issue by katyggls** [new-xkit/XKit#1671]
Since yesterday Blog Tracker is throwing an error next to every tracked blog:

![screenshot](https://i.imgur.com/5MUsCrv.png)

I'm on the latest version of Chrome, latest version of xkit, updated all extensions, etc.

**Comment by nightpool** [comment]
Thanks for reaching out! This is due to the recent Chrome 73 update. Please see our post here for more information: https://new-xkit-extension.tumblr.com/post/183463200189/new-xkit-broken-with-chrome-73.

I'm urgently working on a fix and will let you know when I have a better idea of how long it will take

**Comment by AprilSylph** [comment]
replaced by the more encapsulating #1672
