### ISSUE TITLE
Can't reach XKit servers

### ISSUE THREAD

**Issue by trans-cuchulainn** [new-xkit/XKit#1679]
I keep getting the "could not update new XKit" popup in the bottom left of my screen. Updated Firefox and reinstalled XKit and now I'm getting an error in the middle too: "Code 101: Can't reach XKit servers".

(I'm on Firefox 66.0.2 (64-bit), if that helps)

**Comment by AprilSylph** [comment]
Please follow [this troubleshooting post](https://new-xkit-support.tumblr.com/post/179958045068/troubleshooting-cant-install-or-update)! If you still need help you can still reply here, but this shouldn't be left as an open issue.

**Comment by trans-cuchulainn** [comment]
I did everything that post said... I thought it could be my adblockers but it's definitely whitelisted and I've never had problems with this before. This has literally only started in the past week. XKit has now stopped working entirely but is still giving me error messages.

**Comment by AprilSylph** [comment]
Can you connect to the github.io address? Does this problem still occur when you disable your other addons entirely?

**Comment by trans-cuchulainn** [comment]
Whoa wild, I didn't change anything and I just opened Tumblr again and now it's working? I guess it heard me talking about it and knew its days were numbered if it didn't sort itself out.

So, uh, false alarm, I guess it's working now. Which is confusing because it hasn't been working for a while. But I'm not complaining.

**Comment by AprilSylph** [comment]
Most likely, your adblocker was blocking connections (since normal whitelisting usually won't do anything) but then the filter list with the offending github.io block was updated, removing the root cause of the problem.

To ensure your adblocker doesn't do this again, I can't recommend [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) enough, and it can be configured to not block any requests from other addons as detailed in the troubleshooting post.

**Comment by trans-cuchulainn** [comment]
Yeah, I actually use uBlock Origin already, which is why I was confused that it was doing this! But I think another add-on might've been screwing with it since the last Firefox update? Anyway, it's fixed now, fingers crossed...
