### ISSUE TITLE
Header Options errors out if Tweaks is not installed before it

### ISSUE THREAD

**Issue by Foxwells** [new-xkit/XKit#1682]
Firefox 66.0.2, XKit 7.8.2, Header Options 2.5.3

Essentially what the title says - I load up tumblr, but Header Options doesn't load. I have to disable then re-enable every load of a page for it to work. Admittedly this isn't a terribly important issue, but an annoying one.

"Reduce max width of header to match the dashboard" doesn't work at all, even with turning it off then back on.

**Comment by AprilSylph** [comment]
what extensions do you have installed? I feel like the second thing at least is a weird interaction with Tweaks, specifically if Tweaks isn't installed. pretty sure I knew about this and then forgot, whoops.

it'd be interesting to see if you still need to disable and re-enable with Tweaks installed too!

**Comment by Foxwells** [comment]
Sorry for the delay. I do have Tweaks installed. It's on version 5.7.1 which I think is the latest. Disabling/re-enabling Header Options and then Tweaks, then refreshing causes it to load properly, but only for the first refresh. After that, it breaks again.

**Comment by AprilSylph** [comment]
that's extremely odd. I can't imagine what could cause it to break between one refresh and another, especially without changing any settings...

is XKit Main giving errors about Header Options in the browser console on pageload?
(CTRL+SHIFT+J if tumblr is your only tab, CTRL+SHIFT+I > Console if otherwise; filter to only "Logs" and "Errors")

also, if it comes to it, it'd be useful to have you in our Discord server so I could test your XKit config myself and debug things that way!

---

Changing from bug to unconfirmed for now since this is such a specific problem

**Comment by Foxwells** [comment]
![Screenshot_57](https://user-images.githubusercontent.com/15647033/55657630-79c80600-57c0-11e9-82f7-8a6bdbe0dd92.png)

**Comment by AprilSylph** [comment]
huh! i didnt know it happened with Tweaks simply installed afterwards

you should be able to solve this by simply uninstalling and reinstalling Header Options, but I'll keep this issue open since that's a weird and very unintended requirement
(I'll change the issue name if you can confirm that that works)

**Comment by Foxwells** [comment]
That does indeed fix it, it seems. I install extensions alphabetically so that I can find them easier - you can't sort them or anything from what I know, so. Y'know :d

But yay, thanks xD
