### ISSUE TITLE
Distribute an official Firefox extension

### ISSUE THREAD

**Issue by 9999years** [new-xkit/XKit#1729]
Commit 11e42ba1f87cd7314fbc4b532711842b85daf85f adds a warning to users of [New XKit (W Edition)](https://addons.mozilla.org/en-US/firefox/addon/new-xkit-w/) warning them that it's unofficial (despite the extension's page clearly saying that "This is the W edition, which is unofficial and unaffiliated with the New XKit team.") and chiding them for not using the official version.

1. Install from the GitHub releases page isn't really a distribution pipeline -- it requires manual effort from the users and isn't as clear as just visiting addons.mozilla.org.
2. In my opinion, it's quite rude to release a patch which breaks W Edition for being "unofficial" while not providing an official extension on AMO. While I *can* install from the releases page here, it requires a good few more steps, clearly sidesteps AMO (the official and intended add-on distribution platform), and doesn't sync between browsers -- all offenses at *least* as bad as a user maintaining their own copy because supporting Firefox hasn't been a high priority so far.

Am I missing some context here? It's certainly fairly frustrating to have my workflow broken like this; b91550f7aa8a297da4e3a84c1af5c206167584cc notes that W Edition is "in clear violation of Mozilla's policies for listed add-ons" but doesn't say what those violations are, or link to more information.

**Comment by AprilSylph** [comment]
The AMO policy New XKit violates is [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Reviews#Development_Practices), and the extension page was only updated with that disclaimer after we added the warning. We **will not** distribute the Firefox extension on AMO unless this policy changes, and all the concerns we have stated in the warning are legitimate.

I don't see what's wrong with installing from the GitHub releases page. At worst, we should be adding a note on each release page saying "just click the `.xpi` file link to install!", but we don't get enough support requests asking how to do that to justify it.

Also, this patch doesn't "break" W Edition. It just informs users of the very real potential consequences that using it may have, which would still be present without the warning. I understood that some people may be fine with the risks involved for the sake of their current convenience, which is why I included the option to dismiss the warning forever.

**Comment by AprilSylph** [comment]
Also, self-distributed addons aren't "sidestepping" AMO - if anything, W Edition is sidestepping AMO policy by taking advantage of the lack of human reviews required to remove addons that violate its policies. Mozilla acknowledges self-distributed addons and even [has a term for them](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Agreement#4._Distribution_certificates_review_process).
