### ISSUE TITLE
enhanced queue is missing, but my previous settings still override regular queue

### ISSUE THREAD

**Issue by spdys** [new-xkit/XKit#1842]

**Comment by AprilSylph** [comment]
You're thinking of Queue 2.0, the Tumblr Labs option. Since it hasn't been implemented in the new dashboard yet, but still overrides your default queue settings, you can [turn it off here](https://www.tumblr.com/settings/labs). I had the same problem.

Enhanced Queue only provides one-time actions (queue shuffling and clearing) and cosmetic options (shrinking posts and hiding the queue scheduler), and has no bearing on the queue schedule.
