### ISSUE TITLE
can't like posts from post page

### ISSUE THREAD

**Issue by kitsunegari101** [new-xkit/XKit#1980]
So far it seems to only happen on specific themes (maybe?), but I can't seem to like posts when I have a direct link to them; the option just isn't there in the upper right corner and is instead replaced with a 'Follow [blog name]' button, even when I'm logged in.

![but i'm logged in](https://user-images.githubusercontent.com/14188767/91664774-eed36400-eab6-11ea-9c8e-0abcb242dc2d.png)

Any way I can potentially fix this myself, by tweaking the settings of whatever extension might be causing this, or is this a known problem that's already being worked on?

**Comment by nightpool** [comment]
Is there anything that indicates this might be an XKit problem? Does it
still happen when you disable XKit in your browser's settings?

**Comment by AprilSylph** [comment]
this isn't anything to do with XKit; either your browser's privacy settings or a privacy addon is causing this. it's more likely to happen on blogs with a custom domain, since the blog controls are actually in a `www.tumblr.com` iframe, but some privacy settings/addons may also consider `www.tumblr.com` to be cross-origin when on `blogname.tumblr.com`.
