### ISSUE TITLE
[Feature request] Revive photosets

### ISSUE THREAD

**Issue by JapanYoshi** [new-xkit/XKit#2022]
Tumblr has made it impossible to make any new Photosets from the app or the browser. ([x](https://thefizzynator.tumblr.com/post/637999973330501632) [x](https://thefizzynator.tumblr.com/post/638003932597272576))

![image](https://user-images.githubusercontent.com/8707990/102707357-9a5e2980-42dd-11eb-8d93-8e3910f09c23.png)

Instead of making a specific Photoset Post, it makes a Text Post with inline images. While (I think) this removes the 10-image cap, it makes it impossible to click to zoom in and navigate between images on the browser.

Could there be an XKit extension that allows for making a new post as a Photoset Post?

[Addendum] I've reported this issue to Tumblr Support already, BTW.

**Comment by AprilSylph** [comment]
legacy post types are being deprecated. the real problem here is both with your theme and tumblr's NPF photoset lightbox code - these posts display fine on my theme, where i have `{NewPostStyles}` implemented and "Use new post types" enabled ([x](https://workbench.sylph.tech/private/638012529357062144/tumblr_qlmjgjx3461scs9f3), [x](https://workbench.sylph.tech/private/638012419189391360/tumblr_qlmme4G6Ly1scs9f3)), but Tumblr's lightbox JS is throwing an error in the console when trying to click the larger image on that egg-crafting post.

hopefully Tumblr Support can help, since this seems specific to that photoset - NPF photosets only comprising of larger images [still seem to be fine](https://workbench.sylph.tech/post/182470672853).

for now, you should be able to still make legacy Photoset posts on the web client if your viewport is wide enough to show the full Tumblr dashboard (990px+). but i think it's safe to say that we won't be building our own legacy Photoset post form, or at least not into XKit - the complexity of replicating Tumblr's photoset uploader is far more suited to its own web app, or maybe a standalone browser addon.

**Comment by AprilSylph** [comment]
ah, i see why they aren't displayed properly on your theme - i had to specify `.tmblr-full` as being full-width in my theme code! this should really be provided by Tumblr, but here's the CSS you need:
```css
figure.tmblr-full img {
  width: 100%;
}
```

**Comment by JapanYoshi** [comment]
> these posts display fine on my theme, where i have `{NewPostStyles}` implemented and "Use new post types" enabled

How do I use `{NewPostStyles}`? I've taken another look at the Tumblr theme documentation page, but it doesn't mention it anywhere.
