### ISSUE TITLE
Old "No Sidebar" seems to work better

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#237]
From an ask:

>I still have the old "no sidebar" extension on my xkit from xcloud. It works way better than the new one in open tabs. For one, the open tabs extension EVEN WITH THE FIRST OPTION TURNED OFF opens links twice in 2 new tabs. I didn't want any of them opening in new tabs to begin with I don't actually want that extension. And the sidebar blogs still show up if you click usernames in private blog dashes or in drafts or basically anywhere other than the dash. The old one covered all of them.

**Comment by nightpool** [comment]
needs one of either "unconfirmed" or "bug".

**Comment by rosalindwills** [comment]
I can't reproduce the "two new tabs" thing. The second part is a result of the new preference on "Open in Tabs" to apply only to links in the dashboard. This was intended to prevent the action of clicking things like "Reply to fan mail" from opening in a new tab, but since it also prevents opening blogs on the activity page and such, this needs further investigation.

Perhaps instead of restricting it to the dash, we should restrict it to only applying to user blog links?

**Comment by blackjackkent** [comment]
I can't reproduce the "two new tabs" thing. The second part is a result of the new preference on "Open in Tabs" to apply only to links in the dashboard. This was intended to prevent the action of clicking things like "Reply to fan mail" from opening in a new tab, but since it also prevents opening blogs on the activity page and such, this needs further investigation.

Perhaps instead of restricting it to the dash, we should restrict it to only applying to user blog links?
