### ISSUE TITLE
Blog tracker: track unlimited blogs

### ISSUE THREAD

**Issue by wooziwoozi** [new-xkit/XKit#297]
I don't know if this is the place to put it, but I sent an ask, but then realized the Tumblr is probably swamped, and thought maybe here was a better place to put this. (I can type more here, anyway.)

Anyway, I was wondering if there is any way we could make a new extension, or modify, the current blog tracker extension. (Which seems to be broken for me at the moment.) First of all, it would be nice if you could bookmark more than 10 blogs. (Xkit guy said this wasn't possible because the post numbers would break, but I don't care about the posts numbers.) Secondly, when you would click on the blog it could either open in View On Dash (Please no, it has never worked with photosets.) or ~~the default Tumblr sidebar-for-blogs-you-click-on-thing-that-pops-up-on-the-right-idk-what-to-call-it.~~ in peepr. This way you could closely follow more than 10 blogs, and easily view them without leaving your dash.

Reasons I want this extension, because some of you may be thinking "Just unfollow the blogs you don't want to see then!!" I want to see all blogs that I follow, but I also follow about 400... So it isn't practical for me to see every single post on my dash. I also have a lot of friends I have made on Tumblr, and this number is over 10. My friends and I tend to talk to each other in tags, so it has become a habit of mine to check their blogs daily before I venture out into the wilds known as my dash. Having this extension would allow me to quickly click, view in ~~sidebar-thing~~ peepr, and check for tags, and then be on my merry way.

Anyway, thank you for reading. Now I shall go and keep my fingers crossed. Ahahahahah.

**Comment by nightpool** [comment]
there's another tracking issue for problems with blog tracker sitting
around here somewhere....

@bvtsang I know you're working on tangentially related blog tracker
things—thoughts on this?

I've always wanted some kind of "groups" like view for tumblr... something
like the google+ circles setup where you could have multiple "dashboards"
and could customize what shows up for each one. Definitely a different
extension though haha.

(btw the "Tumblr
sidebar-for-blogs-you-click-on-thing-that-pops-up-on-the-right-idk-what-to-call-it"
is called peepr fwiw)

**Comment by bvtsang** [comment]
Brief thoughts:

- On tracking more than 10 blogs: sounds doable. I think the tradeoff here is the more blogs you track, the slower the extension gets (because it needs to check each blog for posts), but as long as the user knows this it could be fine. We might even support unlimited blogs given that warning.
- On adding an option to choose between opening the blog in View On Dash or the peepr: gonna be honest, I have never seen or touched peepr code, so I don't know how that works. I'll have to look into it.
- Personally I'm more likely to see an ask or a request if it's posted on Github. If it's posted on Tumblr, another mod will probably see it and just repost the issue here.

After I handle the other issue assigned to me (#57), I'll look into this one. For now, I'll assign this to myself so that I don't lose track of it.

@nightpool Thanks for bringing this to my attention!

**Comment by wooziwoozi** [comment]
@bvtsang I asked Xkit guy if he could lift the limit a long time ago, and he said that Tumblr only allows up to 10 blogs to show post numbers. I think that is true, because can't you only by default track a certain number of tags and see the post numbers as well? I think a warning after 10 blogs would fix this though, because for me, and I am sure others, I don't care to know if they have updated, as I plan on clicking to check manually, anyway. (And tbh even with the number notifications, they tend to be wrong, so I ignore them.)

If you could figure out the Peepr thing that would be great, but don't sweat it if you can't. 

Anyway, thank you so much for looking into this. I appreciate it a lot. ♥ (And in general the revival of Xkit, and everything you are doing for us!)

**Comment by bvtsang** [comment]
I'm going to split this issue into three:

1. Track unlimited blogs (this issue)
2. Allow user to click through photosets when viewing a tracked blog
3. Categorize tracked blogs
