### ISSUE TITLE
blacklist doesn't work after reblog-list update

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#416]
>I know you guys said none of you had gotten the update yet, but I just wanted to give you a heads up that Blacklist stopped working when the update hit me.

from the askbox

http://new-xkit-support.tumblr.com/post/128208736168/i-know-you-guys-said-none-of-you-had-gotten-the

**Comment by blackjackkent** [comment]
As near as I can tell, Blacklist still works for tags and usernames, but post content is getting lost for any reblogged content (i.e. it still works on original posts or on content added by a particular post, but any previous reblogs are ignored) because the reblog list update changed the HTML structure of posts.

Steps to reproduce:
1. Make a text post on Tumblr containing a word you wish to block.
2. Observe that post is blocked.
3. Reblog the post.
4. Observe that post is no longer blocked.

I'm looking into this.
