### ISSUE TITLE
Sending asks from dashboard with User Menus+ fails

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#42]

**Comment by Fevix** [comment]
My bad. ColtCelestia here, I didn't realize there was a github. 

More information about the failure, at least the version I'm getting: 
Nothing crashes, as far as I can tell, but the browser does appear to be downloading information (As evidenced by the favicon part of the tab turning into the blue (Chrome) or green (Firefox) animated circle), but after a while it stops that, Chrome opting to display a 'webpage unavailable' page

Edit: It seems that the behavior has changed, now I'm being redirected to the blog's main Ask page (Rather than getting the in-dashboard popup box as per my settings)

**Comment by bvtsang** [comment]
I'm having trouble reproducing this with the following steps, which assumes you have control over accounts A and B:

1. On Account A, make sure User Menus+ is enabled
2. Visit your dashboard
3. Hover your mouse over Account B's avatar
4. In the popup, click on the User Menu and click Ask a Question
5. Anonymously or not, type a message and click Ask
6. On Account B, expect to receive the ask

This currently works for me.

**Comment by Wolvan** [comment]
I get redirected to the blog B's ask page instead of having a popup ask box open. I'll see if I can do something about that tomorrow

**Comment by bvtsang** [comment]
If I turn enable XKit's Classic User Menu, then at step 4 I get redirected to the user's ask page.

**Comment by WyohKnott** [comment]
Because the normal menu popup is handle by a Tumblr event.
Maybe we should trigger it ourselves:
```javascript
 Tumblr.Events.trigger('indashblog:tumblelog:ask', {
    recipient: this.model.get('name'),
    anonymous_asks: this.model.get('anonymous_asks')
  });
```
But I don't like that we rely on inject script so much.

**Comment by bvtsang** [comment]
I've tried https://gist.github.com/bvtsang/b879bee8a960566c0c68, but nothing happens. I guess I'll keep investigating this in the meantime.
