### ISSUE TITLE
Source doesn't appear in the post

### ISSUE THREAD

**Issue by lleytonc** [new-xkit/XKit#423]
This is the post on Chrome with the new xkit installed. 
![5fd554b2-36c4-4c07-b95b-d4ca6687802c](https://cloud.githubusercontent.com/assets/14104016/9650789/9d54617a-523a-11e5-89b7-e28c4cd64727.png)
This is the post on Safari.
![a9163bff-8eca-4d93-aa3f-e09beb303e78](https://cloud.githubusercontent.com/assets/14104016/9650796/ad541e4e-523a-11e5-8114-ba6d8189669d.png)

I also cannot see the update of tumblr coming out today, which kills blockquote. My dash on chrome is still the old version. But if i open tumblr in safari, I can see the new post format just as well. It almost seems that xkit covers some stuff

**Comment by jaygold56** [comment]
I had the same problem that I thought was xkit but it turns out it wasn't. If you have tumblr savior installed I'd check the settings tab and see if you have "Hide Tumblr's source attribution" unchecked. 

As for the new post format, not everyone has this update yet. Tumblr is rolling it out slowly to only some users at a time.

**Comment by lleytonc** [comment]
Ohhhh it's tumblr savior this little shit! This problem has troubled me for so long. Thank you so much!

**Comment by jaygold56** [comment]
No problem :)
