### ISSUE TITLE
One Click Postage doesn't autotag in blog sidebar

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#52]
Probably an issue with frame_run

**Comment by WyohKnott** [comment]
Okay I found where it's not working. When accessing ```XKit.extensions.auto_tagger.preferences``` from within an iframe, the preferences fetched are not the ones saved but the default ones instead.

Hence, it fails to add the tags because the following condition is false:
```javascript
		if (XKit.extensions.auto_tagger.preferences.keep_tags.value) {
			to_return = this.mreturn_add(to_return, obj.tags);
		}
```

Same with the rest of the preferences, for example custom tags for Video post.

**Comment by WyohKnott** [comment]
Welp, auto_tagger is not allowed to run in frame, we just need to switch it on in the header:
```
//* FRAME true **//
```
