### ISSUE TITLE
"External Image" showig up instead of the actual images in posts

### ISSUE THREAD

**Issue by anakhasilver** [new-xkit/XKit#551]
Unsure if this is brand new or what, but I reblogged something and got "External Images" even in the editor. It didn't matter if I had Xkit on or not, it still happened. But if anyone can fix it, you can.

**Comment by ThePsionic** [comment]
@anakhasilver, do you have Auto Load Images installed or not?

**Comment by anakhasilver** [comment]
Yes. It appears that it's an issue where Chrome and Tumblr don't get along for some reason.

**Comment by finagle29** [comment]
There seem to be two issues here:
* "External Image" placeholder showing in the post editor instead of the actual image (which could be interpreted as a problem / deficiency with Auto Load Images)
* After reblogging with ER, the text "External Image" shows instead of a clickable placeholder or the actual image itself

**Comment by anakhasilver** [comment]
That's exactly it. It seems to clear up on its own after awhile, but it's still a bug.

**Comment by AprilSylph** [comment]
essentially resolved since tumblr now hosts any images inserted in text posts. external images only exist if intentionally created with the HTML editor, or on posts made before... 2014, at a guess. closing
