### ISSUE TITLE
Duplicate Text In Reblogged Posts on Sideview

### ISSUE THREAD

**Issue by ShareNoMimosa** [new-xkit/XKit#671]
![screen shot 2015-10-24 at 11 46 58 pm](https://cloud.githubusercontent.com/assets/8609540/10714361/08318472-7aaa-11e5-81ee-5dcda2129aff.png)

i looked at the html and the first is a "reblog-list" div and the second is a "xkit-better-reblogs-old" div

**Comment by ThePsionic** [comment]
Duplicate of #670, but closing that one in favor of this more useful issue.

**Comment by 00Davo** [comment]
Checked it out a little more. The flat-style reblogs are hidden using the CSS:
```css
ol.posts .reblog-list {
  display: none !important;
}
```
This selector doesn't match in sidebars because for no particular reason the sidebars use `<div class="posts">` instead of a list. Just matching the class "posts", rather than `ol.posts`, would work but might apply to other elements unintentionally.

**Comment by nightpool** [comment]
Hmm. Okay I'll take a look at this. The sidebars used to use an ol, which
required a few hacks to get work. Looks like Tumblr changed that.

I'll get a bug fix out today.

**Comment by nightpool** [comment]
fixed by #672
