### ISSUE TITLE
reblogging deactivated source breaks

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#675]
reblog [this](http://scarlet-benoit-is-my-rolemodel.tumblr.com/post/131883809051/cutelildork-at-karaoke-bar-what-the-fuck-do)
get 
![image](https://cloud.githubusercontent.com/assets/233815/10717521/537e2ac0-7b31-11e5-9bef-3195e0d235a2.png)
(plus the normal text and stuff too this is just the part that's broken)
which turns into
![image](https://cloud.githubusercontent.com/assets/233815/10717523/6347acd8-7b31-11e5-8f8d-a567a5aa90dd.png)

**Comment by nightpool** [comment]
this post also has similar issues: http://winterqueenmab.tumblr.com/post/131946998719/dewchan7865-roman-rory-fallen-angel

**Comment by theyliveforever** [comment]
This happens to me even when the sources aren't deactivated. For example, I reblogged [this post](http://1vm.tumblr.com/post/131608296311/atypicalwhitekid-yungricegod) and got this:
![screenshot-www tumblr com 2015-11-02 17-41-28](https://cloud.githubusercontent.com/assets/4481356/10893745/297e6b32-8189-11e5-871d-e4ef6d71c1b2.png)

It only showed up properly when I disabled ER, but I had to disable RDO as well because it always multiplies the captions several times, at least when on nested format. [This](http://queerhawkeye.tumblr.com/post/132419517842/futchlesbianwerewolf-in-yr-otp-whos-the) is another post with the same problem; in this case the source *is* deactivated:
![screenshot-www tumblr com 2015-11-02 17-50-28](https://cloud.githubusercontent.com/assets/4481356/10893994/a4884e82-818a-11e5-8964-eff3925f0d2e.png)

(I commented on that one by copy-pasting a tag from the person I reblogged it from)

**Comment by citrusella** [comment]
@theyliveforever If it helps, RDO only *visually* duplicates the posts, in the posting form. They aren't actually duplicated when it gets reblogged.

This post was completely unrelated to the topic at hand, but I felt weird not bringing it up.

**Comment by theyliveforever** [comment]
@citrusella Thanks! In any case, I always draft so I can check what it looks like before posting.

**Comment by citrusella** [comment]
So, this issue is happening for me, too, now that I'm playing around with editable reblogs... but only on the dash. If I then go in and try to edit to make them show up, they disappear from the html source as well and will disappear on-blog if saved.

http://citrusella-flugpucker.tumblr.com/post/136215027453/thugilly-sakuyandere-perlexnoire-bluhippy

On blog:
![Post shows appropriately on blog](https://cloud.githubusercontent.com/assets/14182450/12044099/fb48c7aa-ae59-11e5-824c-2785784660ae.png)
On dash:
![Post is missing deactivated people on dash](https://cloud.githubusercontent.com/assets/14182450/12044098/fb461cc6-ae59-11e5-9d5f-9348fc77e7f5.png)

**Comment by nightpool** [comment]
closing and repopening becuase there's a similar issue happening but it has a different-ish root cause
