### ISSUE TITLE
Poor extension uninstall handling

### ISSUE THREAD

**Issue by Wolvan** [new-xkit/XKit#762]
I realized this when I was working on #761 earlier and un/reinstalled XWidgets to get a clean slate. It looks that on uninstalling an extension, contrary to what I expected, the settings for said extension do not get deleted from storage. Once I reinstall, the settings are there like they were before uninstalling.

This means that all the storage extensions take up will never get removed if you don't manually reset it first

**Comment by 0xazure** [comment]
Possibly counter-intuitively, I actually like this design.  It probably wasn't intentional, but it's nice that if a user ever accidentally uninstalls an extension, or changes their mind after uninstalling an extension, they haven't lost all of their settings.  Given how many users were waiting for an easy upgrade process to New XKit which preserved their settings, it's clear many users spend a long time setting up XKit just the way they want.  To lose all of that customization due to a mis-click would be annoying in the least and many many hours of re-customization at worst.

Yes, XCloud fills some of this gap in terms of creating restore points, but given that XCloud is 1) optional and 2) a manual process, it's not the only solution.

I would propose an interstitial when a user goes through the uninstall flow that gives them the option to completely remove extension settings data, but I don't feel it should be the default.

**Comment by Wolvan** [comment]
I agree with you on it not being default, we could make it like some uninstaller on windows that ask you if you also want to remove the userdata

**Comment by nightpool** [comment]
I like the idea of putting another section in "Other" in that shows what
data extensions have stored and lets you delete it

**Comment by 0xazure** [comment]
> I like the idea of putting another section in "Other"

The issue there is discoverability.  No matter how many times we make a blogpost or how obvious we make it in the FAQ/docs/etc, it won't be self-evident.  I could be wrong, but I don't see "Other" as a high-traffic pane.
