### ISSUE TITLE
Timestamps and Alternative Timestamps should be combined somewhat

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#800]
All I'm seeing is "failed to load timestamp why?". Using latest version of Chrome.

**Comment by BobbySig** [comment]
This sounds like an issue with the new-ish "Hide blog from not logged in users" feature Tumblr''s got. Unless the new xkit team decides to swap to using API v2 (which may not be entirely possible), this issue will continue existing. There's a "fix" described in the support chat archives [here](https://gitter.im/new-xkit/support/archives/2015/11/22) (just search for "timestamp"), but it's just using the Alternative Timestamps extension instead of just Timestamps. I'm considering adding Alternative Timestamp's parsing as an error case in the original Timestamps, but I'll have to ask the person who created Alt Timestamps extension first.

**Comment by gloomykid** [comment]
Yeah, I'm using the Alternative Timestamps now and hope it won't occur anymore.

**Comment by jesskay** [comment]
@BobbySig Hi, dunno if you sent an ask already and it went awol, but I'll say right now that you're free to incorporate anything from Alternative Timestamps into the regular extension.

Personally I wouldn't mind a toggle to *always* use that parsing since then I could entirely switch (getting timestamps from the API is *really* slow for me on one of the connections I use, so having another option was why I made AT), but feel free to do whatever. :+1:

**Comment by BobbySig** [comment]
@jesskay Thanks. I'm all in favor of removing the API calls from Timestamps entirely, but unfortunately, there are some issues with that.

1. It wouldn't work in the Inbox because staff haven't provided any time data there, and
2. the timestamp Tumblr puts in the posts is what time it is in the time zone you've told Tumblr each blog is in, and changing that can be annoying, especially if someone's got a lot of different blogs.

So for now I'm looking into fiddling with Timestamps to see if there's a good way to isolate the part that figures out the post's timing from the rest of it so I can put a nice clean if statement in there somewhere that falls back to parsing rather than failure, as well as a setting to make it swap to only parsing on the dashboard if a user wants. (Wow that sentence is long.) I'll keep looking, but right now school is ramping up for its bi-annual finale and I'm 100% not ready, so I probably won't start doing it seriously until class is out for winter break.
