### ISSUE TITLE
post your crushes broken?

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#853]
from the inbox:
>Hello new x-kit team! For some reason the 'post my crush' button isn't working. Whenever I press the button, it states that "Server returned a non-JSON object' and suggests I've hit my post limit or account was suspended (neither of which are true)

**Comment by starrla89** [comment]
Same thing happened to me when I tried to post crushes today.

**Comment by designsbybriana** [comment]
I've tried safari, firefox and chrome on my macbook today and every single browser gave me this error. Please look at this issue. Thank you!

**Comment by finagle29** [comment]
I've been able to reproduce this using XKit 7.7.1 on Chrome.  The issue appears to be in how the post object Post Crushes sends to /svc/update is constructed, because Tumblr doesn't like our request.  `response.errors = ["Error saving post"]` is all the debugging info Tumblr replies with, but I'm pretty sure that its caused by an error in constructing the post object.

**Comment by nightpool** [comment]
works for me now....

**Comment by nightpool** [comment]
fixed in https://github.com/new-xkit/XKit/pull/958
