### ISSUE TITLE
ER: reblogging post breaks it

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#893]
1. see that [this post](http://seananmcguire.tumblr.com/post/135387701185/captainpunkrogers-life-hack-be-best-friends) appears just fine on your dash:

   ![image](https://cloud.githubusercontent.com/assets/233815/12043140/8398e03a-ae47-11e5-9c1b-c7688a169226.png)

2. reblog it with editable reblogs ([reblog here](http://nightpool.tumblr.com/private/136210468970/tumblr_npv48mA1lX1rcr256))
3. see that it doesn't appear on your dash:

   ![image](https://cloud.githubusercontent.com/assets/233815/12043144/90342386-ae47-11e5-874e-da2637649abf.png)

4. reblog it without editable reblogs ([reblog here](http://nightpool.tumblr.com/private/136211067460/tumblr_npv48mA1lX1rcr256))
5. see that it works:

    ![image](https://cloud.githubusercontent.com/assets/233815/12043158/be2f742a-ae47-11e5-87fe-f193d2227239.png)

6. be very very sad

**Comment by nightpool** [comment]
editable reblogs was a Bad Idea

**Comment by dlmarquis** [comment]
Do we know for sure that this is ER's fault and not whatever staff is doing that's intermittently causing this problem on all text posts? i.e., is this a Tumblr problem that disproportionately affects ER posts or an actual ER bug?

**Comment by nightpool** [comment]
ER triggering bad tumblr behavior is an ER bug.

**Comment by reecefinch** [comment]
Not sure if this is still open but wanted to comment and say if you reblog with editable reblogs and edit the whole post with 'control+.' or 'control+-' tumblr effectively thinks it's all new text and doesn't erase it but it does add your url to the top.

Alternatively, I've found that editable reblogs is only messing up because the top url can no longer be read / something happens to it's class or label or something and that makes it disappear.

**Comment by nightpool** [comment]
ancient.
