### ISSUE TITLE
Chrome 47 shenanigans

### ISSUE THREAD

**Issue by dlmarquis** [new-xkit/XKit#927]
Lots of asks saying XKit is not loading or throwing errors left and right (OCP, xinbox, others?) with the most recent Chrome update (47?).

**Comment by achillese** [comment]
I'm seconding this problem, in a way — when I visit Tumblr on Chrome, it takes up to a minute or more for me to be able to scroll up and down the dash, the activity page, or even on someone's blog without the screen freezing. I did some (minor) troubleshooting and disabled xkit to see if that was the problem — sure enough, the problem was fixed upon disabling xkit.

**Comment by nightpool** [comment]
Can you post your extension info dump? (This is a separate bug, anyway)

**Comment by nightpool** [comment]
ancient, chrome version 53 is most modern
