### ISSUE TITLE
xcloud doesn't work on safari

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#930]
unconfirmed, from the ask box

>Don't know if you're aware, but XCloud on Safari is broken. I get an error when trying to sign in. I can successfully sign in on Chrome, though. Importing settings doesn't work either.

someone should look into this

**Comment by nightpool** [comment]
can't reproduce on my end, waiting for more information.

**Comment by toddmbloom** [comment]
Just was looking for information on this since I was having some problems too - when I click on restore from xcloud, it just shows the box for 'restoring extensions' for a while but with no progress bar.

![screen shot 2016-03-10 at 17 37 52](https://cloud.githubusercontent.com/assets/348390/13687038/08be9368-e6e7-11e5-98a0-b38c4d389a9c.png)

This is the console:

![screen shot 2016-03-10 at 17 40 09](https://cloud.githubusercontent.com/assets/348390/13687069/2f36768c-e6e7-11e5-8e0b-33fbf69b3c27.png)

**Comment by toddmbloom** [comment]
Hello, 

It was originally synced on Chrome and then restored - using the same account - on Safari. I tried a backup and restore from local file too, but I got the same result.  But when I do it on Firefox - from Chrome original xcloud data - it is working.

**Comment by nightpool** [comment]
Probably related to the Safari/base64 weirdness but I can't find an extant issue for that so closing in favor of making a new issue.
