### ISSUE TITLE
Throwing errors on all blogs in Chrome when logged in

### ISSUE THREAD

**Issue by wiki-howard** [new-xkit/XKit#945]
Steps to reproduce:

1. Go to http://new-xkit-extension.tumblr.com/ (or any blog) with the developer console open
2. Observe this error: `Uncaught TypeError: Cannot read property 'allTumblelogs' of undefined`

Looks like it was introduced here:

https://github.com/new-xkit/XKit/pull/943/files#diff-f3c602f5caa159014c2f7557700de10cR130

**Comment by nightpool** [comment]
Okay, so this isn't quite an error (whats the broken behavior here?) but there's a related error when we try to do fallback on line 164

**Comment by hobinjk** [comment]
The injected function should include an `if (Tumblr)`, an `if (Tumblr && Tumblr.dashboardControls && Tumblr.dashboardControls.allTumblelogs`, or a try/catch because we shouldn't have unnecessary exceptions clogging up debugging.

The [fallback](https://github.com/new-xkit/XKit/pull/943/files#diff-f3c602f5caa159014c2f7557700de10cR162) should first check for `XKit.blogs_from_tumblr`, not just length, which I think is the error in it that you're referencing.

**Comment by nightpool** [comment]
@hobinjk yeah, I changed it to add `XKit.blogs_from_tumblr = [];` above window.addEventListener

I'll add a try-catch, I guess.

**Comment by wiki-howard** [comment]
@hobinjk: Yup!

@nightpool: A try/catch would prevent errors, but "feature detecting" by checking that the whole path exists is better. Relying on global variables defined by Tumblr is brittle, especially when they're not consistent between routes.  You're assuming that `Tumblr.dashboardControls.allTumblelogs` is going to be a Backbone collection, but that's not guaranteed. Furthermore, it assumes that `Tumblr.dashboardControls` and `Tumblr` are both defined in the first place.

**Comment by nightpool** [comment]
@wiki-howard Yes, of course it does. that's why we have three layers of feature detection and fallback in that code.
