### ISSUE TITLE
Feature Request: Blockquote Images

### ISSUE THREAD

**Issue by reecefinch** [new-xkit/XKit#948]
Hello, I am requesting ( I hope that is the right terminology ) a feature similar to the 'fullsize gif' tweak where if you check / uncheck a button all images or as tumblr now deigns them 'figures' will be block quoted without going into the html.

Ideally it would literally just a be a feature that found 'figure' and put a blockquote wrap around it. Personally I would love a double block quote but I'm not even sure this is possible or plausible.

If anyone would like to take this idea on I would appreciate it.

**Comment by finagle29** [comment]
I can work on this, but I'd like some input on how it should work.  Is it best to have a checkbox like full size gif that adds a blockquote to all images or would something like double-clicking on the image to add a layer of blockquotes be better (so that multiple layers of blockquotes can be added and the level of blockquotes be controlled individually for each image) with the option to have a maximum level of blockquotes so that if you decide that you dont want an image to be blockquoted you can double-click when an image is at the max to remove all blockquotes on that image?  Or would an option to add or remove a layer of blockquotes in the right-click menu be even better?

**Comment by reecefinch** [comment]
Hi! I'm so pleased to hear you're interested in taking this on. If at all possible it would unbelievably amazing to be able to have multiple layers of block quotes. Specifically the way I and the people I've spoken to interested in this feature would use it like so. I apologize if I use the github editor wrong I'm very new to this site.

I'm including an image of what I'm trying to describe because i'm bad at this. This is what a post looks like normally.
[https://40.media.tumblr.com/663ac7689467452f49be293f34bfaa4d/tumblr_inline_o25m4m69e01u061lz_540.png](url)

What we would like is the option to do this
[https://41.media.tumblr.com/927e67e3885ab233f39e246c90d530db/tumblr_inline_o25m6gaWNq1u061lz_540.png](url)

You see how the second image is double blocked. Some people might have more than one image they need to block quote but we definitely need a right click option or a double click option because we don't want anything in the first block quote altered or messed with at all.

I hope this makes sense. As for the ability of multiple blockquotes, I think most users would only use 3 at most, but there are some that would kill for the maximum functionality as well. At this point I think we would cry if someone could make this a reality. We simply hate going into the html editor and having a quick fix like right click or double click to block quote images would be such a time saver!

**Comment by finagle29** [comment]
I've made it so that double-clicking an image adds a level of blockquotes to it, up to a maximum set as a preference.  Double-clicking an image that has the max number of blockquotes removes the blockquotes surrounding it.  There is a checkbox in the gear menu that toggles whether or not all images should have the maximum number of blockquotes added.  In Chrome (version 48+ with experimental web platform flag enabled) and Firefox options to add and remove one layer of blockquotes to and from an image as well as remove all blockquotes from an image are available in the right click menu.

@new-xkit/admin opinions on if this should be put in Tweaks or a separate extension and also general design/ux feedback?

**Comment by nightpool** [comment]
uh double clicking is a little weird IMO. Could we hijack the tumblr
formatting popup to be more sensible instead?

**Comment by finagle29** [comment]
I can look into triggering Tumblr's formatting popup.  Do you have opinions on a right click context menu and putting this in Tweaks vs a separate extension?

**Comment by reecefinch** [comment]
I like both the double clicking and the right click. I don't understand how you do it through the little menu pop up but i'm SO EXCITED it's working!! Can't wait to try this out! Thanks for doing this guys! I'm sure whatever you come up with will be splendid for us users.

**Comment by finagle29** [comment]
@reecefinch the custom right click menu looks like this in Chrome 48 with the Enable experimental Web Platform features
![image](https://cloud.githubusercontent.com/assets/5816532/12878564/eeb9de56-cdf4-11e5-9792-842a10a89dfb.png)

**Comment by nightpool** [comment]
right click is way too experimental/whatever for me to feel good about
using it, no?

**Comment by reecefinch** [comment]
quick question, how will i know when / if the extension works / is released? will it be reblogged on the new-xkit-extension tumblr?

**Comment by bvtsang** [comment]
@reecefinch An easy way to tell when the extension is released (or when there's a resolution to this bug) would be when this issue is closed.

Alternatively, keep an eye out on our [pull requests](https://github.com/new-xkit/XKit/pulls) to see if @finagle29 or anyone else submitted anything.

**Comment by reecefinch** [comment]
HI! It's been about a month since I last checked up on this thread and I wondered if it had been put aside or quit? I know it seemed very promising above and simply wondered if there had been any progress @finagle29 . thank you. I would love this extension/script even if only for myself, I know you had it some what working there earlier. Thank you again for your hard work and time. I checked the pull requests but  i didn't see anything there.

**Comment by finagle29** [comment]
sorry @reecefinch for letting this slip, i'm still excited to work on this, just got put on the back burner to make room for other life things for a while

we can add things to Tumblr's formatting popup, but the fade-in/fade-out animations are done in Tumblr javascript that doesn't like even a clone of one of its buttons, so it looks weird.

if double clicking seems weird and HTML5 contextmenus too experimental, how about clicking and holding (or a variety of click actions as preferences) to pop up our own context menu? @nightpool 

also, opinions on Tweaks vs. separate extension?

**Comment by AprilSylph** [comment]
closing as now-impossible; NPF doesn't support blockquoted images, they display as just images on the new dashboard
