### ISSUE TITLE
Readmore using TinyURL instead of blog URL

### ISSUE THREAD

**Issue by Wolvan** [new-xkit/XKit#971]
From TumblrIM

ellirph
Hey, I had a question and thought you might be able to answer it. I found out that the tumblr TinyURLs are connected straight to the primary account, regardless of URL name (so you can change your Tumblr URL, but your TinyURL stays the same). Is there any way to script or code the Read Mores to place the TinyURL instead of your Tumblr URL?

ellirph
Or, is there a way that could be changed and thus someone could request an extension? I'm thinking it would be helpful when there are resource blogs that change their URLs to be able to use the TinyURL option so their content stays seamless

bigger-better-yee-haw
not quite sure what you mean, what tiny url option? And how should it be placed in read mores?

ellirph
So, for our Tumblr URLS, we can change those to be anything. Like mine is ellirph but I could change it to followerofzuul if I wanted, and any read mores that I place before the change that other's have reblogged would still say ellirph
Thus, needing a redirect

bigger-better-yee-haw
ah

ellirph
But, permalinks actually have a data-post-tiny-url that is unique to an account, despite the URL chosen

bigger-better-yee-haw
unfortunately I don't think that's possible

ellirph
Damn

bigger-better-yee-haw
since the readmore gets generated by tumblr

ellirph
I was hoping there was a way to change it to the data-post-tiny-url instead of the tumblr url
OK. Well, thanks anyway ^_^

bigger-better-yee-haw
At least I don't have an idea how that would work right now
I'll open a github issue though, if you want

ellirph
No worries. I knew it was way beyond my technical level, so I thought of XKit since you guys are more techy than I am
It would definitely be cool; I didn't want to request anything though without checking since I know there are limitations on what you guys can alter.

**Comment by ElliSpeaks** [comment]
To clarify, this is a question of whether the top-level domain links can be changed in Read Mores.
With Tumblr, we can change our URLs at any time, so this year I might be ellirph.tumblr.com, but maybe I want to change it to zuul.tumblr.com next year. Any content I posted with Read Mores still direct to ellirph.tumblr.com/posturl. BUT, if you look at the tiny-url created when you @ someone on Tumblr, a unique code is generated to that account, and that code STAYS regardless of how many times you change your URL. For instance, mine is http://tmblr.co/mW_yJmcLOewcMTNhkFx5Y1A and no matter what I change ellirph vanity to, that link will always stay the same.

SO, is there was a way to change the functionality of the Read More to be that tinyurl code, instead of your tumblr vanity, regardless of how many times you change your URL, the content would always be seamless.

Make sense?

**Comment by nightpool** [comment]
@ElliSpeaks I don't know if we can make tumblr short blogs urls link to a specific post, unfortunately.

**Comment by ElliSpeaks** [comment]
Ah well, makes sense :) I know you guys are limited in what you can do by what Tumblr allows. Thanks anyway ^_^

**Comment by AprilSylph** [comment]
post-specific short URLs do exist but the problem is that they're generated after post creation, so seamlessly adding these links anywhere upon post creation is completely impossible.
maybe this will be truly solved when tumblr embraces UUIDs more, but anything we make that could resolve this would be too janky to be worth having
